### ISSUE TITLE
ESMではrequire()が使用できないとエラーが出て実行できない

### ISSUE THREAD

**Issue by nerusaba-mi** [akikaki-bot/Earthquake_mapmaker#1]
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/**/Downloads/Earthquake_mapmaker/node_modules/d3/src/index.js from /Users/**/Downloads/Earthquake_mapmaker/index.js not supported.
Instead change the require of /Users/**/Downloads/Earthquake_mapmaker/node_modules/d3/src/index.js in /Users/**/Downloads/Earthquake_mapmaker/index.js to a dynamic import() which is available in all CommonJS modules.
    at /Users/**/Downloads/Earthquake_mapmaker/index.js:5:12
    at Object.<anonymous> (/Users/**/Downloads/Earthquake_mapmaker/index.js:470:7) {
  code: 'ERR_REQUIRE_ESM'
}
と出て実行できません。
多分d3がESMで書かれているからだと思います。

**Comment by nerusaba-mi** [comment]
解決しました・・・
すいません
